import type { Metadata, Viewport } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Newsreader } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { ClarityProvider } from "@/components/analytics/ClarityProvider";
import { GoogleAnalytics } from "@/components/analytics/GoogleAnalytics";
import { ChatLauncherGate } from "@/components/chat/ChatLauncherGate";
import { site } from "@/lib/site";
import { cn } from "@/lib/utils";
import "./globals.css";

const newsreader = Newsreader({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-newsreader",
  weight: ["400", "500"],
  style: ["normal", "italic"],
});

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FAF9F6" },
    { media: "(prefers-color-scheme: dark)", color: "#0C0E10" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} — ${site.tagline}`,
    template: `%s · ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  authors: [{ name: site.name }],
  generator: "Next.js",
  keywords: [
    "supplement interactions",
    "drug supplement interaction checker",
    "supplement safety",
    "medication interactions",
    "supplement stack analyzer",
    "evidence-based supplements",
  ],
  referrer: "origin-when-cross-origin",
  creator: site.name,
  publisher: site.name,
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: site.locale,
    url: site.url,
    siteName: site.name,
    title: `${site.name} — ${site.tagline}`,
    description: site.description,
    // OG image auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: `${site.name} — ${site.tagline}`,
    description: site.description,
    // Twitter image auto-generated by src/app/opengraph-image.tsx
    creator: site.twitter,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // Search-engine ownership verification.
  // Drop the codes from each platform into env vars (no code change
  // needed when switching tokens). Next.js emits the appropriate
  // <meta> tags only when the env var is set.
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
    other: {
      "msvalidate.01": process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION ?? "",
      "yandex-verification":
        process.env.NEXT_PUBLIC_YANDEX_SITE_VERIFICATION ?? "",
    },
  },
  category: "health",
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": `${site.url}#organization`,
  name: site.name,
  url: site.url,
  // /icon2.png is the 512×512 PNG emitted by src/app/icon2.png
  // (was `/logo.png` which 404'd — fixed).
  logo: {
    "@type": "ImageObject",
    url: `${site.url}/icon2.png`,
    width: 512,
    height: 512,
  },
  description: site.description,
  email: site.email,
  address: {
    "@type": "PostalAddress",
    addressLocality: "Boston",
    addressRegion: "MA",
    addressCountry: site.country,
  },
  sameAs: [
    `https://twitter.com/${site.twitter.replace("@", "")}`,
    "https://linkedin.com/company/pharmaguide",
    "https://instagram.com/pharmaguide.io",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={cn(
        GeistSans.variable,
        GeistMono.variable,
        newsreader.variable,
        "scroll-smooth antialiased"
      )}
      suppressHydrationWarning
    >
      <head>
        {/* Icons emitted automatically by Next.js from
            src/app/icon.tsx (32×32 favicon)
            src/app/apple-icon.tsx (180×180 iOS home)
            src/app/icon1.tsx (192×192 PWA)
            — no manual <link> tags needed.                          */}
        <link rel="manifest" href="/manifest.webmanifest" />
        <script
          type="application/ld+json"
          // Schema.org Organization tag — boosts knowledge graph + GEO targeting
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-screen bg-background text-foreground">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[600] focus:rounded-md focus:bg-ink focus:px-4 focus:py-2 focus:text-white"
        >
          Skip to content
        </a>
        {children}
        {/* Floating "Ask PharmaGuide AI" chat launcher. Hidden on
            legal/disclosure routes; fades in after first scroll past
            the hero on every other page. See ChatLauncherGate. */}
        <ChatLauncherGate />
        <Analytics />
        <SpeedInsights />
        <ClarityProvider />
        <GoogleAnalytics />
      </body>
    </html>
  );
}
